spring:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/

  mail:
    host: smtp.gmail.com
    port: 587
    username: hungtran6360
    password: weapsadpimnqtkfv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  output:
    ansi:
      enabled: ALWAYS

  main:
    allow-circular-references: true

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://admin:admin@mongo-aufgabe-dev.671lr.mongodb.net/launchpad-dev?retryWrites=true&w=majority
      database: launchpad-dev

server:
  endpoint: http://localhost:8080
